const data = [
	{
		id: "fm-theme-switcher",
		name: "fm-theme-switcher",
		title: "Social Media Dashboard",
		link: "https://fm-theme-switcher-anna.netlify.app/",
		source: "./images/projects/social.jpeg",
		type: "image/jpeg",
		img: "./images/projects/social.jpeg",
		tags: ["react"],
		repo: "https://github.com/annacsillaxs/FM_social_media_dashboard",
		desc: "Simple Social Media Dashboard React app with dark and light mode toggle function. Static data. Design from Frontend Mentor.",
	},
	{
		id: "clock",
		name: "clock",
		featured: false,
		title: "Themed Clock App",
		link: "https://js-clock-theme.netlify.app/",
		source: "./images/projects/clock.jpg",
		type: "image/jpg",
		img: "./images/projects/clock.jpg",
		tags: ["html", "css", "js"],
		repo: "https://github.com/annacsillaxs/js-clock-theme",
		desc: "Clock App with theme switcher function built with JavaScript. Idea based on Brad Traversy's Theme Clock Project from 50 Projects in 50 Days Udemy Course.",
	},
	{
		id: "iptracker",
		featured: true,
		name: "IPTracker",
		title: "IP Address Tracker App",
		link: "https://ip-tracker-fm-anna.netlify.app/",
		source: "./images/projects/tracker.png",
		type: "image/png",
		img: "./images/projects/tracker.png",
		tags: ["html", "css", "js", "api"],
		repo: "https://github.com/annacsillaxs/FM-IP-Address_tracker",
		desc: "JavaScript App based on a Frontend Mentor Challenge. To get the IP Address locations, I used the IP Geolocation API by IPify. To generate the map, I used LeafletJS.",
		links: ["https://leafletjs.com/", "https://geo.ipify.org/"],
		href: ["LeafletJS", "IP Geolocation API"],
	},
	{
		id: "greenByte",
		name: "greenByte",
		title: "GreenByte Site",
		link: "https://green-byte-landing.netlify.app/",
		source: "./images/projects/gb.jpg",
		type: "image/jpg",
		img: "./images/projects/gb.jpg",
		tags: ["html", "css"],
		repo: "https://github.com/annacsillaxs/greenbyte",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
	{
		id: "relaxer",
		name: "relaxer",
		title: "Relaxer JS App",
		link: "https://js-relaxer-app.netlify.app/",
		source: "./images/projects/relax.jpg",
		type: "image/jpg",
		img: "./images/projects/relax.jpg",
		tags: ["html", "css", "js"],
		repo: "https://github.com/annacsillaxs/js-relaxer-app",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
	{
		id: "rgba",
		name: "rgba game",
		title: "RGBA Guessing Game",
		link: "https://rgba-color-guessing-game.netlify.app/",
		source: "./images/projects/rgba.jpg",
		type: "image/jpg",
		img: "./images/projects/rgba.jpg",
		tags: ["html", "css", "js"],
		repo: "https://github.com/annacsillaxs/ColorGuessingGame",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
	{
		id: "dadjokes",
		name: "dadjokes api",
		title: "Dadjokes API",
		link: "https://sobaddajokes.netlify.app/",
		source: "./images/projects/dadjokes.jpg",
		type: "image/jpg",
		img: "./images/projects/dadjokes.jpg",
		tags: ["html", "css", "js", "api"],
		repo: "",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
	{
		id: "infinitescroll",
		name: "infinite scroll",
		title: "Infinite Scroll",
		link: "https://infinite-scroll-blog.netlify.app/",
		source: "./images/projects/infinitescroll.jpg",
		type: "image/jpg",
		img: "./images/projects/infinitescroll.jpg",
		tags: ["html", "css", "js", "api"],
		repo: "https://github.com/annacsillaxs/infinite-scroll-blog",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
	{
		id: "vertical slider",
		name: "vertical slider",
		title: "Vertical Slider Gallery",
		link: "https://js-vertical-slider-infinite.netlify.app/",
		source: "./images/projects/slider.jpg",
		type: "image/jpg",
		img: "./images/projects/slider.jpg",
		tags: ["html", "css", "js"],
		repo: "https://github.com/annacsillaxs/js-vertical-slider-infinite",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
	{
		id: "dragndrop",
		name: "drag n drop",
		title: "Drag & Drop Puzzle",
		link: "https://js-drag-n-drop-puzzle.netlify.app/",
		source: "./images/projects/dragndrop.jpg",
		type: "image/jpg",
		img: "./images/projects/dragndrop.jpg",
		tags: ["html", "css", "js"],
		repo: "https://github.com/annacsillaxs/js-drag-n-drop-puzzle",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
	{
		id: "lyrics",
		name: "lyrics search",
		title: "Lyrics Search App",
		link: "https://lyrics-search-js-app.netlify.app/",
		source: "./images/projects/lyrics.jpeg",
		type: "image/jpeg",
		img: "./images/projects/lyrics.jpeg",
		tags: ["html", "css", "js", "api"],
		repo: "https://github.com/annacsillaxs/lyrics-search-js-app",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
	{
		id: "sunnyside",
		name: "sunnyside",
		title: "Sunnyside Landing Page",
		link: "https://sunnyside-fm-anna.netlify.app/",
		source: "./images/projects/sunnyside.jpeg",
		type: "image/jpeg",
		img: "./images/projects/sunnyside.jpeg",
		tags: ["html", "css"],
		repo: "https://github.com/annacsillaxs/FM_sunnyside_landing_page",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
	{
		id: "splitter",
		name: "splitter",
		featured: true,
		title: "Tip Splitter React App",
		link: "https://fm-splitter-react-anna.netlify.app/",
		source: "./images/projects/splitter.jpeg",
		type: "image/jpeg",
		img: "./images/projects/splitter.jpeg",
		tags: ["react"],
		repo: "https://github.com/annacsillaxs/FM-splitter-react",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
	{
		id: "minesweeper",
		name: "minesweeper",
		featured: true,
		title: "Minesweeper Retro Game",
		link: "https://minesweeper-anna.netlify.app/",
		source: "./images/projects/minesweeper.jpg",
		type: "image/jpg",
		img: "./images/projects/minesweeper.jpg",
		tags: ["html", "css", "js"],
		repo: "https://github.com/annacsillaxs/minesweeper",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
	{
		id: "coffeeroasters",
		name: "coffeeroasters",
		featured: true,
		title: "Coffeeroasters landing page",
		link: "https://coffeeroasters-fm-anna.netlify.app/",
		source: "./images/projects/coffeeroasters.png",
		type: "image/png",
		img: "./images/projects/coffeeroasters.png",
		tags: ["html", "css", "js"],
		repo: "https://github.com/annacsillaxs/coffeeroasters",
		desc: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Vero eaque, aliquid, officiis fugit esse incidunt at impedit animi sequi modi quod, error tenetur praesentium iure.",
	},
];
export default data;
